# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
parse_spf <- function(spf_rec) {
    .Call('_dnshelpers_parse_spf', PACKAGE = 'dnshelpers', spf_rec)
}

